In [11]:
import pandas as pd
df = pd.read_csv("C:/Rishika_PC/Projects/Incubate/incubate_2025/zone_divided_data.csv")
df

,Patient Name,UMR No.,Reports Photo,Bill No.,Age,Gender,Date,Gram Stain,Organism Isolated,Specimen Type,...,Norfloxacin,Nitrofurantoin,Piperacillin- Tazobactam,Tigecycline,Tobramycin,Trimethoprim,Trimethoprim/Sulfame Thoxale,Vancomycin,patient_id,geo_zone
0,mrs.lankabai vitthal kamble,592892.0,no sensitivity data,ob20087497,72.0,female,2020-11-19,"no pus cells, no organisms seen",no growth,urine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,592892.0,Zone C
1,mrs.shailu pande,646255.0,yes,ob20063359,39.0,female,2020-10-16,"no pus cells, gram negative bacilli seen",acinetobacter spp,urine,...,s,r,NaN,NaN,NaN,NaN,NaN,NaN,646255.0,Zone C
2,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20048586,16.0,male,2020-09-25,no organisms seen,no growth (no turbidity seen),biological indicator (autoclave ),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,695323.0,Zone B
3,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20020625,16.0,male,2020-08-12,no organisms seen,no growth (no turbidity seen ),biological indicator (autoclave),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,695323.0,Zone A
4,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20091394,16.0,male,2020-11-24,minus;,no turbidity seen,biological indicator of autoclave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,695323.0,Zone B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,mrs.vaishali shubhash mate,3008762.0,no sensitivity data,ser0056749,23.0,female,2020-08-12,"many epithelial cells , no pus cells seen, gra...",candida spp,high vaginal swab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008762.0,Zone C
798,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0107858,28.0,male,2020-09-09,"no pus cells, no organisms seen",no growth,central line tip,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone B
799,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0196376,28.0,male,2020-10-25,"occasional pus cells, no organisms seen",no growth,pus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone B
800,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0074681,28.0,male,2020-08-24,"no pus cells, no organisms seen",no growth,tissue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone C
801,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0085112,28.0,male,2020-08-30,"no pus cells, no organisms seen",no growth,urine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone C

In [12]:
df = df[df['UMR No.'].notna()]

In [13]:
df

,Patient Name,UMR No.,Reports Photo,Bill No.,Age,Gender,Date,Gram Stain,Organism Isolated,Specimen Type,...,Norfloxacin,Nitrofurantoin,Piperacillin- Tazobactam,Tigecycline,Tobramycin,Trimethoprim,Trimethoprim/Sulfame Thoxale,Vancomycin,patient_id,geo_zone
0,mrs.lankabai vitthal kamble,592892.0,no sensitivity data,ob20087497,72.0,female,2020-11-19,"no pus cells, no organisms seen",no growth,urine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,592892.0,Zone C
1,mrs.shailu pande,646255.0,yes,ob20063359,39.0,female,2020-10-16,"no pus cells, gram negative bacilli seen",acinetobacter spp,urine,...,s,r,NaN,NaN,NaN,NaN,NaN,NaN,646255.0,Zone C
2,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20048586,16.0,male,2020-09-25,no organisms seen,no growth (no turbidity seen),biological indicator (autoclave ),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,695323.0,Zone B
3,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20020625,16.0,male,2020-08-12,no organisms seen,no growth (no turbidity seen ),biological indicator (autoclave),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,695323.0,Zone A
4,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20091394,16.0,male,2020-11-24,minus;,no turbidity seen,biological indicator of autoclave,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,695323.0,Zone B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,mrs.vaishali shubhash mate,3008762.0,no sensitivity data,ser0056749,23.0,female,2020-08-12,"many epithelial cells , no pus cells seen, gra...",candida spp,high vaginal swab,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008762.0,Zone C
798,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0107858,28.0,male,2020-09-09,"no pus cells, no organisms seen",no growth,central line tip,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone B
799,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0196376,28.0,male,2020-10-25,"occasional pus cells, no organisms seen",no growth,pus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone B
800,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0074681,28.0,male,2020-08-24,"no pus cells, no organisms seen",no growth,tissue,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone C
801,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0085112,28.0,male,2020-08-30,"no pus cells, no organisms seen",no growth,urine,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3008777.0,Zone C

In [18]:
df.isna().sum()

Patient Name                      0
UMR No.                           0
Reports Photo                     0
Bill No.                          0
Age                               0
Gender                            0
Date                              0
Gram Stain                        0
Organism Isolated                 0
Specimen Type                     0
Department                        0
Colony Count                    759
Antibiotic - Sensitive          737
Antibiotic - Susceptible        795
Antibiotic - Intermediate       795
Antibotic - Resistant           740
Amikacin                        688
Amoxicillin                     778
Amoxicillin+Clavulanic Acid     738
Ampicillin                      693
Ampicillin+Sulbactam            783
Azithromycin                    776
Aztreonam                       773
Benzyl Penicillin               775
Cefazolin                       793
Cefepime                        697
Cefotaxime                      718
Cefoxitin                       772
Ceftazidime                     695
Ceftriaxone                     717
Cefuroxime                      730
Cephalexin                      794
Chloramphenicol                 796
Ciprofloxacin                   666
Clarithromycin                  777
Clindamycin                     790
Colistin                        729
Co-Trimoxazole                  694
Doripenem                       775
Ertapenem                       712
Erythromycin                    775
Gentamicin                      665
Imipenem                        670
Levofloxacin                    674
Linezolid                       773
Meropenem                       672
Norfloxacin                     748
Nitrofurantoin                  746
Piperacillin- Tazobactam        752
Tigecycline                     793
Tobramycin                      775
Trimethoprim                    794
Trimethoprim/Sulfame Thoxale    794
Vancomycin                      775
patient_id                        0
geo_zone                          0
dtype: int64

In [17]:
df['Department']=df['Department'].fillna('unknown')

C:\Users\Rishika\AppData\Local\Temp\ipykernel_45924\113350467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Department']=df['Department'].fillna('unknown')

In [30]:
todrop = ['Antibiotic - Sensitive', 'Antibiotic - Susceptible', 'Antibiotic - Intermediate', 'Antibotic - Resistant', 'patient_id','geo_zone']
fdf = df.drop(columns=todrop)
fdf

,Patient Name,UMR No.,Reports Photo,Bill No.,Age,Gender,Date,Gram Stain,Organism Isolated,Specimen Type,Department,Colony Count,Amikacin,Amoxicillin,Amoxicillin+Clavulanic Acid,Ampicillin,Ampicillin+Sulbactam,Azithromycin,Aztreonam,Benzyl Penicillin,Cefazolin,Cefepime,Cefotaxime,Cefoxitin,Ceftazidime,Ceftriaxone,Cefuroxime,Cephalexin,Chloramphenicol,Ciprofloxacin,Clarithromycin,Clindamycin,Colistin,Co-Trimoxazole,Doripenem,Ertapenem,Erythromycin,Gentamicin,Imipenem,Levofloxacin,Linezolid,Meropenem,Norfloxacin,Nitrofurantoin,Piperacillin- Tazobactam,Tigecycline,Tobramycin,Trimethoprim,Trimethoprim/Sulfame Thoxale,Vancomycin
0,mrs.lankabai vitthal kamble,592892.0,no sensitivity data,ob20087497,72.0,female,2020-11-19,"no pus cells, no organisms seen",no growth,urine,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mrs.shailu pande,646255.0,yes,ob20063359,39.0,female,2020-10-16,"no pus cells, gram negative bacilli seen",acinetobacter spp,urine,general medicine,NaN,s,NaN,r,r,NaN,NaN,NaN,NaN,NaN,s,s,NaN,s,s,NaN,NaN,NaN,s,NaN,NaN,s,s,NaN,r,NaN,s,s,r,NaN,s,s,r,NaN,NaN,NaN,NaN,NaN,NaN
2,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20048586,16.0,male,2020-09-25,no organisms seen,no growth (no turbidity seen),biological indicator (autoclave ),unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20020625,16.0,male,2020-08-12,no organisms seen,no growth (no turbidity seen ),biological indicator (autoclave),unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mr.dr.d.y. patil blood bank,695323.0,no sensitivity data,ob20091394,16.0,male,2020-11-24,minus;,no turbidity seen,biological indicator of autoclave,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,mrs.vaishali shubhash mate,3008762.0,no sensitivity data,ser0056749,23.0,female,2020-08-12,"many epithelial cells , no pus cells seen, gra...",candida spp,high vaginal swab,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0107858,28.0,male,2020-09-09,"no pus cells, no organisms seen",no growth,central line tip,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0196376,28.0,male,2020-10-25,"occasional pus cells, no organisms seen",no growth,pus,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0074681,28.0,male,2020-08-24,"no pus cells, no organisms seen",no growth,tissue,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
801,mr.nikhil bhagwan pemare,3008777.0,no sensitivity data,ser0085112,28.0,male,2020-08-30,"no pus cells, no organisms seen",no growth,urine,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
todrop = ['Patient Name', 'Bill No.']
fdf = fdf.drop(columns=todrop)
fdf

,UMR No.,Reports Photo,Age,Gender,Date,Gram Stain,Organism Isolated,Specimen Type,Department,Colony Count,Amikacin,Amoxicillin,Amoxicillin+Clavulanic Acid,Ampicillin,Ampicillin+Sulbactam,Azithromycin,Aztreonam,Benzyl Penicillin,Cefazolin,Cefepime,Cefotaxime,Cefoxitin,Ceftazidime,Ceftriaxone,Cefuroxime,Cephalexin,Chloramphenicol,Ciprofloxacin,Clarithromycin,Clindamycin,Colistin,Co-Trimoxazole,Doripenem,Ertapenem,Erythromycin,Gentamicin,Imipenem,Levofloxacin,Linezolid,Meropenem,Norfloxacin,Nitrofurantoin,Piperacillin- Tazobactam,Tigecycline,Tobramycin,Trimethoprim,Trimethoprim/Sulfame Thoxale,Vancomycin
0,592892.0,no sensitivity data,72.0,female,2020-11-19,"no pus cells, no organisms seen",no growth,urine,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,646255.0,yes,39.0,female,2020-10-16,"no pus cells, gram negative bacilli seen",acinetobacter spp,urine,general medicine,NaN,s,NaN,r,r,NaN,NaN,NaN,NaN,NaN,s,s,NaN,s,s,NaN,NaN,NaN,s,NaN,NaN,s,s,NaN,r,NaN,s,s,r,NaN,s,s,r,NaN,NaN,NaN,NaN,NaN,NaN
2,695323.0,no sensitivity data,16.0,male,2020-09-25,no organisms seen,no growth (no turbidity seen),biological indicator (autoclave ),unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,695323.0,no sensitivity data,16.0,male,2020-08-12,no organisms seen,no growth (no turbidity seen ),biological indicator (autoclave),unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,695323.0,no sensitivity data,16.0,male,2020-11-24,minus;,no turbidity seen,biological indicator of autoclave,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,3008762.0,no sensitivity data,23.0,female,2020-08-12,"many epithelial cells , no pus cells seen, gra...",candida spp,high vaginal swab,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
798,3008777.0,no sensitivity data,28.0,male,2020-09-09,"no pus cells, no organisms seen",no growth,central line tip,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
799,3008777.0,no sensitivity data,28.0,male,2020-10-25,"occasional pus cells, no organisms seen",no growth,pus,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
800,3008777.0,no sensitivity data,28.0,male,2020-08-24,"no pus cells, no organisms seen",no growth,tissue,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
801,3008777.0,no sensitivity data,28.0,male,2020-08-30,"no pus cells, no organisms seen",no growth,urine,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
fdf['Specimen Type'].unique()

array(['urine', 'biological indicator (autoclave )',
       'biological indicator (autoclave)',
       'biological indicator of autoclave', 'blood bag',
       'blood bag ( 2876 prbc) ( 00ci4412)',
       'blood bag (2837 prbc) (00ci1010)',
       'blood bag (2900 prbc) (93vx9284)',
       'blood bag (2906 prbc) (00ci4270)', 'blood bag (3067) (93vj6523)',
       'blood bag (3069) (93vj6702)', 'blood bag (3073) (00i15881)',
       'blood bag (3181) ( 00i26498)',
       'blood bag unit no 2504 prbc (93xc4147)',
       'blood bag unit no 2609 prbc (93xc4111)',
       'blood bag unit no 2622 prbc (93vx9038)',
       'blood bag unit no 2664 prbc (00c14297)',
       'blood bag unit no 2788 plt (00c13691',
       'blood bag unit no 2790 plt (00c10800)',
       'blood bag unit no 2791 plt (00c10863)',
       'blood bag unit no 2792 plt (00c10923)',
       'blood bag unit no 3467 (00pj0958)',
       'blood bag unit no 3468 (00pc9562)',
       'blood bag unit no 3533(plt) (00pc9460)',
       'blood bag unit no 3534(plt) (00pj4522)',
       'blood bag unit no 3541(00pj4549)',
       'blood bag unit no 3588(plt) (00pk1936)',
       'blood bag unit no 3595(plt) (00pk2122)',
       'blood bag unit no 3780 prbc  sample source minus;00pk6245',
       'blood bag unit no 3792 prbc  sample source minus;00pj1283',
       'blood bag unit no 3865 prbc  sample source minus;00pi2462',
       'blood bag unit no 3868 prbc  sample source minus;00pl2415',
       'blood bag unit no 3922 plt  sample source minus;00pj2422',
       'blood bag unit no 3923 plt  sample source minus;00pj0837',
       'blood bag unit no 3924 plt sample source minus;00pj4421',
       'blood bag unit no 4003 plt sample source minus;00pj0726',
       'blood bag unit no: 1991 (pc), segment no: 93ik9630',
       'blood bag unit no: 2001 (pc), segment no: 93ip4587',
       'blood bag unit no: 2077 (pc), segment no: 93ij3258',
       'blood bag unit no: 2087 (pc), segment no: 93iy6037',
       'blood bag unit no: 2171 (plt), segment no: 93ij1203',
       'blood bag unit no: 2176 (plt), segment no : 93ik0838',
       'blood bag unit no: 2178 (plt), segment no: 93ik0894',
       'blood bag unit no: 2179 (plt), segment no: 93ik0761',
       'blood bag unit no: 2312, segment no: 92vx0845',
       'blood bag unit no: 2313, segment no: 92vx0867',
       'blood bag unit no: 2323 prbc, segment no: 92vu8074',
       'blood bag unit no: 2416 prbc, segment no: 92vu8805',
       'blood bag unit no: 2419 prbc, segment no: 92vu8526',
       'blood bag unit no: 2481 plt, segment no: 92vu3764',
       'blood bag unit no: 2483 plt, segment no: 92vu8434',
       'blood bag unit no:2358 prbc, segment no: 92vx0892',
       'bloos bag unit no 3455 (00pc9543)',
       'empty bag tripal (sagm)350 ml (lot no 18b20y2 (seg no 00pj0990)',
       'empty blood bag ( triple saam 350) (25a20x1) (00i24922)',
       'empty blood bag triple (s) 350, segment no: 93vx9136',
       'triple sagam (350ml) blood bag,lot no :181112001 b ,jms,sample source :segment no :h3694054',
       'triple sagam(350ml)blood bag lot no: 85pd05aa00 fresenius kabi',
       'sputum', 'pus', 'stool', 'tissue', 'sinus (discharge)', 'swab',
       'pus swab', 'hvs', 'conjunctive swab', 'pus (foot)',
       'pus (left foot)', 'wound swab', 'endotracheal tube',
       'pus swab(wound))', 'ascitic fluid', 'bal', 'c.s.f.',
       'nail scraping', 'hd catheter tip', 'bone', 'pleural fluid',
       'pus (left malleous)', 'abscess on left thigh', 'pus (lower leg)',
       'synovial fluid', 'high vaginal swab', 'pus (discharging sinus)',
       'hd tip', 'vaginal swab', 'catheter tip', 'pus (upper leg)',
       'pus (blister on foot)', 'peritoneal fluid', 'swab (suture site)',
       'suture site', 'ulcer swab', 'wound swab (suture site)',
       'swab (incision site)', 'biopsy (slough from axillary)',
       'bone tip', 'pus (thigh abscess)', 'tip', 'slough', 'pus (slough)',
       'pus (scrotum)', 'liver abscess', 'pus (d10minus;d11 vertebrae)e',
       'bile', 'pus (sinus tract)', 'tip uvc', 'bile fluid',
       'umbilical tip', 'e.t. tube', 'pus ( from skin graft area)',
       'discharge swab', 'et tip', 'e.t. tip', 'soft tissue',
       'throat swab', 'haematoma (abdominal cavity)',
       'purulent discharge', 'pus (post lscs)',
       'swab (wound gap abdominal cavity)', 'umbilical line tip',
       'pus (tracheostoma)', 'pus (infra umbilical sinus tract)',
       'pus (lymph node)', 'pericardial fluid', 'breast abscess (fluid)',
       'pus (breast abscess)', 'pus (suture site)', 'pus (diabetic foot)',
       'et secretion', 'pus (calf abscess)',
       'gauze from midline abdominal wound', 'pus (axilla)', 'csf',
       'pus (submental region)', 'swab (ulcer over leg)',
       'tissue (left leg)', 'tracheal tube swab', 'tracheostomy tube',
       'radial head', 'vagnial swab', 'umbilical line', 'blood',
       'slough (perineum)', 'central line tip', 'scrotal tissue',
       'e.t. secretions', 'pus (thigh)',
       'biopsy intramuscular paraspinal aspirate', 'bone marrow aspirate',
       'vaginal discharge', 'pus (left leg)', 'pus discharge',
       'right femoral catheter', 'et', 'pus (liver abscess)',
       'pus (bowel loop)', 'discharge (bartholin cyst)',
       'pus (anterior chest wall)', 'oral secretions', 'pus (abdomen)',
       'discharge from wound', 'intercostal drain fluid',
       'pus (midline incision)', 'discharge', 'pu (left knee)',
       'pus (abdominal cavity)', 'granulation tissue', 'pancreatic fluid',
       'discharge (operation site)'], dtype=object)

In [ ]:
import re
from sklearn.preprocessing import MultiLabelBinarizer

def split_gram(x):
    if pd.isnull(x):
        return []
    
    return [v.strip().lower() for v in x.split(',') if v.strip()]


fdf['Gram_List'] = fdf['Gram Stain'].apply(split_gram)


mlb_gram = MultiLabelBinarizer()
gram_dummies = pd.DataFrame(
    mlb_gram.fit_transform(fdf['Gram_List']),
    columns=[f"Gram_{c}" for c in mlb_gram.classes_],
    index=fdf.index
)

fdf = pd.concat([fdf, gram_dummies], axis=1)



def clean_org(x):
    if pd.isnull(x):
        return ''
    s = x.lower()
    
    s = re.sub(r'\([^)]*\)', '', s)
    
    s = re.sub(r'[^a-z0-9,; ]+', ' ', s)
    return s

def split_org(s):
    parts = re.split(r'[;,]| and |\d+\)', s)
    return [p.strip() for p in parts if p.strip()]


fdf['Org_Clean'] = fdf['Organism Isolated'].apply(clean_org)
fdf['Org_List']  = fdf['Org_Clean'].apply(split_org)


mlb_org = MultiLabelBinarizer()
org_dummies = pd.DataFrame(
    mlb_org.fit_transform(fdf['Org_List']),
    columns=[f"Org_{c}" for c in mlb_org.classes_],
    index=fdf.index
)

fdf = pd.concat([fdf, org_dummies], axis=1)



def clean_specimen(x):
    if pd.isnull(x):
        return ''
    s = x.lower()
    
    s = re.split(r'\(|\d', s)[0]
    return s.strip()

fdf['Specimen_Clean'] = fdf['Specimen Type'].apply(clean_specimen)

# now it’s essentially a single‐label categorical variable
spec_dummies = pd.get_dummies(fdf['Specimen_Clean'], prefix='Spec')

fdf = pd.concat([fdf, spec_dummies], axis=1)





fdf.drop(columns=['Gram_List', 'Org_Clean', 'Org_List', 'Specimen_Clean'], inplace=True)

In [34]:
fdf

,UMR No.,Reports Photo,Age,Gender,Date,Gram Stain,Organism Isolated,Specimen Type,Department,Colony Count,Amikacin,Amoxicillin,Amoxicillin+Clavulanic Acid,Ampicillin,Ampicillin+Sulbactam,Azithromycin,Aztreonam,Benzyl Penicillin,Cefazolin,Cefepime,Cefotaxime,Cefoxitin,Ceftazidime,Ceftriaxone,Cefuroxime,Cephalexin,Chloramphenicol,Ciprofloxacin,Clarithromycin,Clindamycin,Colistin,Co-Trimoxazole,Doripenem,Ertapenem,Erythromycin,Gentamicin,Imipenem,Levofloxacin,Linezolid,Meropenem,Norfloxacin,Nitrofurantoin,Piperacillin- Tazobactam,Tigecycline,Tobramycin,Trimethoprim,Trimethoprim/Sulfame Thoxale,Vancomycin,Gram_3minus;4 epithelial cells /oif,Gram_3minus;4/oif epithelial cells,Gram_8minus;10/oif pus cells seen,Gram_< 10 epithelial cells,Gram_<10 epithelial cells,Gram_<10 epithelial cells/lpf,Gram_<10 pus cells,Gram_<10 pus cells/lpf,Gram_> 25 pus cells,Gram_>10 epithelial cells/lpf,Gram_>25 epithelial cells,Gram_>25 epithelial cells/lpf,Gram_>25 pus cells,Gram_>25 pus cells/lpf,Gram_>25/lpf epithelial cells,Gram_budding yeast cells seen,Gram_budding yeast cells seen.,Gram_budding yeast like cells seen,Gram_budding yeast like cells seen.,Gram_budding yeast like cells with pseudohyphae,Gram_epithelial cells <10/lpf,Gram_epithelial cells >25/lpf,Gram_epithelial cells minus;few,Gram_epithelial cells>25 /lpf,Gram_few epithelial cells,Gram_few gram negative bacilli seen,Gram_few pus cells,Gram_gram negative bacilli seen.,Gram_gram [positive cocci in pairs and chains seen,Gram_gram neagtive bacilli seen,Gram_gram neagtive bacilli seen,Gram_gram negative bacilli seen,Gram_gram negative bacilli,Gram_gram negative bacilli and gram positive cocci seen,Gram_gram negative bacilli organisms seen,Gram_gram negative bacilli see.,Gram_gram negative bacilli seen,Gram_gram negative bacilli seen.,Gram_gram negative bacilli seen. seen,Gram_gram negative cocco bacilli seen,Gram_gram negative coccobacilli seen,Gram_gram posiitive cocci in chain seen.,Gram_gram positive budding yeast seen,Gram_gram positive cocci in chains seen,Gram_gram positive cocci in pairs and chain seen,Gram_gram positive bacilli,Gram_gram positive bacilli and gram positive budding yeast like cells seen.,Gram_gram positive bacilli in chain seen,Gram_gram positive bacilli seen,Gram_gram positive bacilli seen.,Gram_gram positive budding,Gram_gram positive budding yeast like cells,Gram_gram positive budding yeast like cells seen,Gram_gram positive budding yeast like cells seen,Gram_gram positive budding yeast like cells seen with pseudohyphae,Gram_gram positive budding yeast like cells seen wiyh pseudohyphae,Gram_gram positive budding yeast like cells seen.,Gram_gram positive budding yeast like cells seen.seen,Gram_gram positive budding yeast like seen,Gram_gram positive cocci,Gram_gram positive cocci in chains,Gram_gram positive cocci in pairs,Gram_gram positive cocci in cluster seen.,Gram_gram positive cocci in chain seen,Gram_gram positive cocci in chain seen.,Gram_gram positive cocci in chain seen.gram negative bacilli seen.,Gram_gram positive cocci in chains seen,Gram_gram positive cocci in chainsand gram negative bacilli seen.,Gram_gram positive cocci in clusters,Gram_gram positive cocci in clusters seen,Gram_gram positive cocci in clusters seen.,Gram_gram positive cocci in pairs and chain seen,Gram_gram positive cocci in pairs and chains seen,Gram_gram positive cocci in pairs and chains seen.,Gram_gram positive cocci in pairs and clusters seen,Gram_gram positive cocci in pairs seen,Gram_gram positive cocci in pairs seen.,Gram_gram positive cocci in single chains,Gram_gram positive cocci seen,Gram_gram positive cocci seen in chains,Gram_gram positive cocci seen in pairs and clusters seen,Gram_gram positive cocci seen.,Gram_gram positive cooci seen,Gram_gram positivecocci in clusters,Gram_many epithelial cells,Gram_many epitheliai cells,Gram_many epithelial cells,Gram_many epithelial cells seen,Gram_many gram negative bacili seen,Gram_many gram negative bacilli seen,Gram_many gram negative bacilli seen.,Gram_many gram negative bailli seen.,Gram_many pus cells,Gram_many pus cells seen,Gram_minus;,Gram_minus;minus;,Gram_minus;minus;minus;,Gram_moderate pus cells,Gram_no pus cells,Gram_no epithelial cell,Gram_no epithelial cells,Gram_no gram negative bacilli seen,Gram_no organism seen,Gram_no organism seen.,Gram_no organisms seen,Gram_no organisms seen.,Gram_no pus cells,Gram_no pus cells seen,Gram_no puscells,Gram_no puss cells,Gram_occ epithelial cells,Gram_occ pus cells,Gram_occasional pus cells,Gram_occasional epithelial cells,Gram_occasional epithelial cells seen,Gram_occasional epithelial cells seen.gram positive cocci in chain seen.,Gram_occasional epithelial cells.occasional pus cells,Gram_occasional pu cells,Gram_occasional pus cell,Gram_occasional pus cells,Gram_occasional pus cells occasional epithelial cell seen,Gram_occasional pus cells seen,Gram_occasional pus cells.,Gram_occational epithelial cells,Gram_occational epithelial cells,Gram_occational pus cells,Gram_pccasional epithelial cells,Gram_plenty of epithelial cells,Gram_plenty pus cells,Gram_pus cells 7minus;8/oif,Gram_pus cells <10 / lpf,Gram_pus cells <10/lpf,Gram_pus cells >25 / lpf,Gram_pus cells minus;few,Gram_pus cells<10 / lpf,Gram_pus cells<10/lpf,Org_1 klebsiella pneumoniae 2 proteus mirabilis,Org_1 klebsiella pneumoniae 2 methicillin resistant staphylococcus aureus,Org_1 proteus mirabilis 2 klebsiella pneumoniae,Org_1 pseudomonas aeruginosa 2 klebsiella pneumoniae,Org_1 klebsiella pneumoniae 2 proteus mirabilis,Org_1 klebsiella pneumoniae 2 pseudomonas aeruginosa,Org_1 klebsiella pneumoniae 2 proteus mirabilis,Org_1 methicillin resistant staphylococcus aureus 2 pseudomonas aeruginosa,Org_1 proteus mirabilis,Org_1 proteus mirabilis 2 pseudomonas aeruginosa,Org_2 pseudomonas aeruginosa,Org_acinetobacter baumannii,Org_acinetobacter species,Org_acinetobacter spp,Org_candida s pp,Org_candida species,Org_candida spp,Org_candida spp grown,Org_coagulase negative staphylococci seen,Org_coagulase negative staphylococcus,Org_e coli,Org_enterobacter aureus,Org_enterobacter cloacae,Org_enterobacter spp,Org_enterococcus faecium,Org_enterococcus fecalis,Org_enterococcus spp,Org_group a beta haemolytic streptococcus,Org_klebsiella pneumoniae,Org_methicillin resistant coagulase negative staphylococci,Org_methicillin resistant coagulase negative staphylococcus,Org_methicillin resistant cogulase negative staphylococcus,Org_methicillin resistant cogulase negative staphylococcus,Org_methicillin resistant staphylococcus aureus,Org_methicillin resistant staphylococcus epidermidis,Org_no growth,Org_no growth,Org_no growth after 48 hours of incubation,Org_no growth of pathogenic organism in culture,Org_no organism seen,Org_no pathogenic growth,Org_no pathogens grown,Org_no pathogens grown commensals isolated,Org_no pus cells,Org_no significant growth,Org_no turbidity seen,Org_non pathogenic growth,Org_non pathogenic organism growth,Org_non pathogenic organism growth,Org_nonminus,Org_pathogenic growth,Org_proteus mirabilis,Org_proteus vulgaris,Org_pseudomonas aeruginosa,Org_pseudomonas aeruginosaklebsiella pneumoniae,Org_pseudomonas putida,Org_pseudomonas spp,Org_staphylococcus aureus,Spec_abscess on left thigh,Spec_ascitic fluid,Spec_bal,Spec_bile,Spec_bile fluid,Spec_biological indicator,Spec_biological indicator of autoclave,Spec_biopsy,Spec_biopsy intramuscular paraspinal aspirate,Spec_blood,Spec_blood bag,Spec_blood bag unit no,Spec_blood bag unit no:,Spec_bloos bag unit no,Spec_bone,Spec_bone marrow aspirate,Spec_bone tip,Spec_breast abscess,Spec_c.s.f.,Spec_catheter tip,Spec_central line tip,Spec_conjunctive swab,Spec_csf,Spec_discharge,Spec_discharge from wound,Spec_discharge swab,Spec_e.t. secretions,Spec_e.t. tip,Spec_e.t. tube,Spec_empty bag tripal,Spec_empty blood bag,Spec_empty blood bag triple,Spec_endotracheal tube,Spec_et,Spec_et secretion,Spec_et tip,Spec_gauze from midline abdominal wound,Spec_granulation tissue,Spec_haematoma,Spec_hd catheter tip,Spec_hd tip,Spec_high vaginal swab,Spec_hvs,Spec_intercostal drain fluid,Spec_liver abscess,Spec_nail scraping,Spec_oral secretions,Spec_pancreatic fluid,Spec_pericardial fluid,Spec_peritoneal fluid,Spec_pleural fluid,Spec_pu,Spec_purulent discharge,Spec_pus,Spec_pus discharge,Spec_pus swab,Spec_radial head,Spec_right femoral catheter,Spec_scrotal tissue,Spec_sinus,Spec_slough,Spec_soft tissue,Spec_sputum,Spec_stool,Spec_suture site,Spec_swab,Spec_synovial fluid,Spec_throat swab,Spec_tip,Spec_tip uvc,Spec_tissue,Spec_tracheal tube swab,Spec_tracheostomy tube,Spec_triple sagam,Spec_ulcer swab,Spec_umbilical line,Spec_umbilical line tip,Spec_umbilical tip,Spec_urine,Spec_vaginal discharge,Spec_vaginal swab,Spec_vagnial swab,Spec_wound swab
0,592892.0,no sensitivity data,72.0,female,2020-11-19,"no pus cells, no organisms seen",no growth,urine,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,646255.0,yes,39.0,female,2020-10-16,"no pus cells, gram negative bacilli seen",acinetobacter spp,urine,general medicine,NaN,s,NaN,r,r,NaN,NaN,NaN,NaN,NaN,s,s,NaN,s,s,NaN,NaN,NaN,s,NaN,NaN,s,s,NaN,r,NaN,s,s,r,NaN,s,s,r,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
2,695323.0,no sensitivity data,16.0,male,2020-09-25,no organisms seen,no growth (no turbidity seen),biological indicator (autoclave ),unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,695323.0,no sensitivity data,16.0,male,2020-08-12,no organisms seen,no growth (no turbidity seen ),biological indicator (autoclave),unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,695323.0,no sensitivity data,16.0,male,2020-11-24,minus;,no turbidity seen,biological indicator of autoclave,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,3008762.0,no sensitivity data,23.0,female,2020-08-12,"many epithelial cells , no pus cells seen, gra...",candida spp,high vaginal swab,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
798,3008777.0,no sensitivity data,28.0,male,2020-09-09,"no pus cells, no organisms seen",no growth,central line tip,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
799,3008777.0,no sensitivity data,28.0,male,2020-10-25,"occasional pus cells, no organisms seen",no growth,pus,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd


print(fdf.isna().sum().to_string())

UMR No.                                                                          0
Reports Photo                                                                    0
Age                                                                              0
Gender                                                                           0
Gram Stain                                                                       0
Organism Isolated                                                                0
Specimen Type                                                                    0
Department                                                                       0
Colony Count                                                                     0
Amikacin                                                                       688
Amoxicillin                                                                    778
Amoxicillin+Clavulanic Acid                                                    738
Ampicillin                                                                     693
Ampicillin+Sulbactam                                                           783
Azithromycin                                                                   776
Aztreonam                                                                      773
Benzyl Penicillin                                                              775
Cefazolin                                                                      793
Cefepime                                                                       697
Cefotaxime                                                                     718
Cefoxitin                                                                      772
Ceftazidime                                                                    695
Ceftriaxone                                                                    717
Cefuroxime                                                                     730
Cephalexin                                                                     794
Chloramphenicol                                                                796
Ciprofloxacin                                                                  666
Clarithromycin                                                                 777
Clindamycin                                                                    790
Colistin                                                                       729
Co-Trimoxazole                                                                 694
Doripenem                                                                      775
Ertapenem                                                                      712
Erythromycin                                                                   775
Gentamicin                                                                     665
Imipenem                                                                       670
Levofloxacin                                                                   674
Linezolid                                                                      773
Meropenem                                                                      672
Norfloxacin                                                                    748
Nitrofurantoin                                                                 746
Piperacillin- Tazobactam                                                       752
Tigecycline                                                                    793
Tobramycin                                                                     775
Trimethoprim                                                                   794
Trimethoprim/Sulfame Thoxale                                                   794
Vancomycin                                                                     775
Gram_3minus;4 epithelial cells /oif                                              0
Gram_3minus;4/oif epithelial cells                                               0
Gram_8minus;10/oif pus cells seen                                                0
Gram_< 10 epithelial cells                                                       0
Gram_<10 epithelial cells                                                        0
Gram_<10 epithelial cells/lpf                                                    0
Gram_<10 pus cells                                                               0
Gram_<10 pus cells/lpf                                                           0
Gram_> 25 pus cells                                                              0
Gram_>10 epithelial cells/lpf                                                    0
Gram_>25 epithelial cells                                                        0
Gram_>25 epithelial cells/lpf                                                    0
Gram_>25 pus  cells                                                              0
Gram_>25 pus cells/lpf                                                           0
Gram_>25/lpf epithelial cells                                                    0
Gram_budding yeast cells seen                                                    0
Gram_budding yeast cells seen.                                                   0
Gram_budding yeast like cells seen                                               0
Gram_budding yeast like cells seen.                                              0
Gram_budding yeast like cells with pseudohyphae                                  0
Gram_epithelial cells <10/lpf                                                    0
Gram_epithelial cells >25/lpf                                                    0
Gram_epithelial cells minus;few                                                  0
Gram_epithelial cells>25 /lpf                                                    0
Gram_few epithelial cells                                                        0
Gram_few gram negative bacilli seen                                              0
Gram_few pus cells                                                               0
Gram_gram  negative bacilli seen.                                                0
Gram_gram [positive cocci in pairs  and chains seen                              0
Gram_gram neagtive bacilli  seen                                                 0
Gram_gram neagtive bacilli seen                                                  0
Gram_gram negative  bacilli seen                                                 0
Gram_gram negative bacilli                                                       0
Gram_gram negative bacilli and  gram positive cocci seen                         0
Gram_gram negative bacilli organisms seen                                        0
Gram_gram negative bacilli see.                                                  0
Gram_gram negative bacilli seen                                                  0
Gram_gram negative bacilli seen.                                                 0
Gram_gram negative bacilli seen. seen                                            0
Gram_gram negative cocco bacilli seen                                            0
Gram_gram negative coccobacilli seen                                             0
Gram_gram posiitive cocci in chain seen.                                         0
Gram_gram positive  budding yeast seen                                           0
Gram_gram positive  cocci in chains seen                                         0
Gram_gram positive  cocci in pairs and chain seen                                0
Gram_gram positive bacilli                                                       0
Gram_gram positive bacilli and gram positive budding yeast like cells seen.      0
Gram_gram positive bacilli in chain seen                                         0
Gram_gram positive bacilli seen                                                  0
Gram_gram positive bacilli seen.                                                 0
Gram_gram positive budding                                                       0
Gram_gram positive budding yeast like  cells                                     0
Gram_gram positive budding yeast like  cells seen                                0
Gram_gram positive budding yeast like cells seen                                 0
Gram_gram positive budding yeast like cells seen with pseudohyphae               0
Gram_gram positive budding yeast like cells seen wiyh pseudohyphae               0
Gram_gram positive budding yeast like cells seen.                                0
Gram_gram positive budding yeast like cells seen.seen                            0
Gram_gram positive budding yeast like seen                                       0
Gram_gram positive cocci                                                         0
Gram_gram positive cocci  in chains                                              0
Gram_gram positive cocci  in pairs                                               0
Gram_gram positive cocci in  cluster seen.                                       0
Gram_gram positive cocci in chain seen                                           0
Gram_gram positive cocci in chain seen.                                          0
Gram_gram positive cocci in chain seen.gram negative bacilli seen.               0
Gram_gram positive cocci in chains seen                                          0
Gram_gram positive cocci in chainsand gram negative bacilli seen.                0
Gram_gram positive cocci in clusters                                             0
Gram_gram positive cocci in clusters seen                                        0
Gram_gram positive cocci in clusters seen.                                       0
Gram_gram positive cocci in pairs and chain seen                                 0
Gram_gram positive cocci in pairs and chains seen                                0
Gram_gram positive cocci in pairs and chains seen.                               0
Gram_gram positive cocci in pairs and clusters seen                              0
Gram_gram positive cocci in pairs seen                                           0
Gram_gram positive cocci in pairs seen.                                          0
Gram_gram positive cocci in single chains                                        0
Gram_gram positive cocci seen                                                    0
Gram_gram positive cocci seen in chains                                          0
Gram_gram positive cocci seen in pairs and clusters seen                         0
Gram_gram positive cocci seen.                                                   0
Gram_gram positive cooci seen                                                    0
Gram_gram positivecocci in clusters                                              0
Gram_many  epithelial cells                                                      0
Gram_many epitheliai cells                                                       0
Gram_many epithelial cells                                                       0
Gram_many epithelial cells seen                                                  0
Gram_many gram negative bacili seen                                              0
Gram_many gram negative bacilli seen                                             0
Gram_many gram negative bacilli seen.                                            0
Gram_many gram negative bailli seen.                                             0
Gram_many pus cells                                                              0
Gram_many pus cells seen                                                         0
Gram_minus;                                                                      0
Gram_minus;minus;                                                                0
Gram_minus;minus;minus;                                                          0
Gram_moderate pus cells                                                          0
Gram_no  pus cells                                                               0
Gram_no epithelial cell                                                          0
Gram_no epithelial cells                                                         0
Gram_no gram  negative bacilli seen                                              0
Gram_no organism seen                                                            0
Gram_no organism seen.                                                           0
Gram_no organisms seen                                                           0
Gram_no organisms seen.                                                          0
Gram_no pus cells                                                                0
Gram_no pus cells seen                                                           0
Gram_no puscells                                                                 0
Gram_no puss cells                                                               0
Gram_occ epithelial cells                                                        0
Gram_occ pus cells                                                               0
Gram_occasional  pus cells                                                       0
Gram_occasional epithelial cells                                                 0
Gram_occasional epithelial cells seen                                            0
Gram_occasional epithelial cells seen.gram positive cocci in chain seen.         0
Gram_occasional epithelial cells.occasional pus cells                            0
Gram_occasional pu cells                                                         0
Gram_occasional pus cell                                                         0
Gram_occasional pus cells                                                        0
Gram_occasional pus cells occasional epithelial cell seen                        0
Gram_occasional pus cells seen                                                   0
Gram_occasional pus cells.                                                       0
Gram_occational  epithelial cells                                                0
Gram_occational epithelial cells                                                 0
Gram_occational pus cells                                                        0
Gram_pccasional epithelial cells                                                 0
Gram_plenty of epithelial cells                                                  0
Gram_plenty pus cells                                                            0
Gram_pus cells 7minus;8/oif                                                      0
Gram_pus cells <10 / lpf                                                         0
Gram_pus cells <10/lpf                                                           0
Gram_pus cells >25 / lpf                                                         0
Gram_pus cells minus;few                                                         0
Gram_pus cells<10 / lpf                                                          0
Gram_pus cells<10/lpf                                                            0
Org_1  klebsiella pneumoniae 2  proteus mirabilis                                0
Org_1  klebsiella pneumoniae 2 methicillin resistant staphylococcus aureus       0
Org_1  proteus mirabilis 2  klebsiella pneumoniae                                0
Org_1  pseudomonas aeruginosa 2  klebsiella pneumoniae                           0
Org_1 klebsiella pneumoniae  2  proteus mirabilis                                0
Org_1 klebsiella pneumoniae  2 pseudomonas aeruginosa                            0
Org_1 klebsiella pneumoniae 2  proteus  mirabilis                                0
Org_1 methicillin resistant staphylococcus aureus  2 pseudomonas aeruginosa      0
Org_1 proteus mirabilis                                                          0
Org_1 proteus mirabilis 2  pseudomonas aeruginosa                                0
Org_2  pseudomonas aeruginosa                                                    0
Org_acinetobacter baumannii                                                      0
Org_acinetobacter species                                                        0
Org_acinetobacter spp                                                            0
Org_candida s pp                                                                 0
Org_candida species                                                              0
Org_candida spp                                                                  0
Org_candida spp grown                                                            0
Org_coagulase negative staphylococci  seen                                       0
Org_coagulase negative staphylococcus                                            0
Org_e coli                                                                       0
Org_enterobacter aureus                                                          0
Org_enterobacter cloacae                                                         0
Org_enterobacter spp                                                             0
Org_enterococcus faecium                                                         0
Org_enterococcus fecalis                                                         0
Org_enterococcus spp                                                             0
Org_group a beta haemolytic streptococcus                                        0
Org_klebsiella pneumoniae                                                        0
Org_methicillin resistant coagulase negative staphylococci                       0
Org_methicillin resistant coagulase negative staphylococcus                      0
Org_methicillin resistant cogulase negative  staphylococcus                      0
Org_methicillin resistant cogulase negative staphylococcus                       0
Org_methicillin resistant staphylococcus aureus                                  0
Org_methicillin resistant staphylococcus epidermidis                             0
Org_no  growth                                                                   0
Org_no growth                                                                    0
Org_no growth after 48 hours of incubation                                       0
Org_no growth of pathogenic organism in culture                                  0
Org_no organism seen                                                             0
Org_no pathogenic growth                                                         0
Org_no pathogens grown                                                           0
Org_no pathogens grown  commensals isolated                                      0
Org_no pus cells                                                                 0
Org_no significant growth                                                        0
Org_no turbidity seen                                                            0
Org_non pathogenic growth                                                        0
Org_non pathogenic organism  growth                                              0
Org_non pathogenic organism growth                                               0
Org_nonminus                                                                     0
Org_pathogenic growth                                                            0
Org_proteus mirabilis                                                            0
Org_proteus vulgaris                                                             0
Org_pseudomonas aeruginosa                                                       0
Org_pseudomonas aeruginosaklebsiella pneumoniae                                  0
Org_pseudomonas putida                                                           0
Org_pseudomonas spp                                                              0

In [36]:
fdf['Colony Count']=fdf['Colony Count'].fillna('unknown')

In [38]:
fdf=fdf.drop('Date', axis=1)

In [39]:
fdf

,UMR No.,Reports Photo,Age,Gender,Gram Stain,Organism Isolated,Specimen Type,Department,Colony Count,Amikacin,Amoxicillin,Amoxicillin+Clavulanic Acid,Ampicillin,Ampicillin+Sulbactam,Azithromycin,Aztreonam,Benzyl Penicillin,Cefazolin,Cefepime,Cefotaxime,Cefoxitin,Ceftazidime,Ceftriaxone,Cefuroxime,Cephalexin,Chloramphenicol,Ciprofloxacin,Clarithromycin,Clindamycin,Colistin,Co-Trimoxazole,Doripenem,Ertapenem,Erythromycin,Gentamicin,Imipenem,Levofloxacin,Linezolid,Meropenem,Norfloxacin,Nitrofurantoin,Piperacillin- Tazobactam,Tigecycline,Tobramycin,Trimethoprim,Trimethoprim/Sulfame Thoxale,Vancomycin,Gram_3minus;4 epithelial cells /oif,Gram_3minus;4/oif epithelial cells,Gram_8minus;10/oif pus cells seen,Gram_< 10 epithelial cells,Gram_<10 epithelial cells,Gram_<10 epithelial cells/lpf,Gram_<10 pus cells,Gram_<10 pus cells/lpf,Gram_> 25 pus cells,Gram_>10 epithelial cells/lpf,Gram_>25 epithelial cells,Gram_>25 epithelial cells/lpf,Gram_>25 pus cells,Gram_>25 pus cells/lpf,Gram_>25/lpf epithelial cells,Gram_budding yeast cells seen,Gram_budding yeast cells seen.,Gram_budding yeast like cells seen,Gram_budding yeast like cells seen.,Gram_budding yeast like cells with pseudohyphae,Gram_epithelial cells <10/lpf,Gram_epithelial cells >25/lpf,Gram_epithelial cells minus;few,Gram_epithelial cells>25 /lpf,Gram_few epithelial cells,Gram_few gram negative bacilli seen,Gram_few pus cells,Gram_gram negative bacilli seen.,Gram_gram [positive cocci in pairs and chains seen,Gram_gram neagtive bacilli seen,Gram_gram neagtive bacilli seen,Gram_gram negative bacilli seen,Gram_gram negative bacilli,Gram_gram negative bacilli and gram positive cocci seen,Gram_gram negative bacilli organisms seen,Gram_gram negative bacilli see.,Gram_gram negative bacilli seen,Gram_gram negative bacilli seen.,Gram_gram negative bacilli seen. seen,Gram_gram negative cocco bacilli seen,Gram_gram negative coccobacilli seen,Gram_gram posiitive cocci in chain seen.,Gram_gram positive budding yeast seen,Gram_gram positive cocci in chains seen,Gram_gram positive cocci in pairs and chain seen,Gram_gram positive bacilli,Gram_gram positive bacilli and gram positive budding yeast like cells seen.,Gram_gram positive bacilli in chain seen,Gram_gram positive bacilli seen,Gram_gram positive bacilli seen.,Gram_gram positive budding,Gram_gram positive budding yeast like cells,Gram_gram positive budding yeast like cells seen,Gram_gram positive budding yeast like cells seen,Gram_gram positive budding yeast like cells seen with pseudohyphae,Gram_gram positive budding yeast like cells seen wiyh pseudohyphae,Gram_gram positive budding yeast like cells seen.,Gram_gram positive budding yeast like cells seen.seen,Gram_gram positive budding yeast like seen,Gram_gram positive cocci,Gram_gram positive cocci in chains,Gram_gram positive cocci in pairs,Gram_gram positive cocci in cluster seen.,Gram_gram positive cocci in chain seen,Gram_gram positive cocci in chain seen.,Gram_gram positive cocci in chain seen.gram negative bacilli seen.,Gram_gram positive cocci in chains seen,Gram_gram positive cocci in chainsand gram negative bacilli seen.,Gram_gram positive cocci in clusters,Gram_gram positive cocci in clusters seen,Gram_gram positive cocci in clusters seen.,Gram_gram positive cocci in pairs and chain seen,Gram_gram positive cocci in pairs and chains seen,Gram_gram positive cocci in pairs and chains seen.,Gram_gram positive cocci in pairs and clusters seen,Gram_gram positive cocci in pairs seen,Gram_gram positive cocci in pairs seen.,Gram_gram positive cocci in single chains,Gram_gram positive cocci seen,Gram_gram positive cocci seen in chains,Gram_gram positive cocci seen in pairs and clusters seen,Gram_gram positive cocci seen.,Gram_gram positive cooci seen,Gram_gram positivecocci in clusters,Gram_many epithelial cells,Gram_many epitheliai cells,Gram_many epithelial cells,Gram_many epithelial cells seen,Gram_many gram negative bacili seen,Gram_many gram negative bacilli seen,Gram_many gram negative bacilli seen.,Gram_many gram negative bailli seen.,Gram_many pus cells,Gram_many pus cells seen,Gram_minus;,Gram_minus;minus;,Gram_minus;minus;minus;,Gram_moderate pus cells,Gram_no pus cells,Gram_no epithelial cell,Gram_no epithelial cells,Gram_no gram negative bacilli seen,Gram_no organism seen,Gram_no organism seen.,Gram_no organisms seen,Gram_no organisms seen.,Gram_no pus cells,Gram_no pus cells seen,Gram_no puscells,Gram_no puss cells,Gram_occ epithelial cells,Gram_occ pus cells,Gram_occasional pus cells,Gram_occasional epithelial cells,Gram_occasional epithelial cells seen,Gram_occasional epithelial cells seen.gram positive cocci in chain seen.,Gram_occasional epithelial cells.occasional pus cells,Gram_occasional pu cells,Gram_occasional pus cell,Gram_occasional pus cells,Gram_occasional pus cells occasional epithelial cell seen,Gram_occasional pus cells seen,Gram_occasional pus cells.,Gram_occational epithelial cells,Gram_occational epithelial cells,Gram_occational pus cells,Gram_pccasional epithelial cells,Gram_plenty of epithelial cells,Gram_plenty pus cells,Gram_pus cells 7minus;8/oif,Gram_pus cells <10 / lpf,Gram_pus cells <10/lpf,Gram_pus cells >25 / lpf,Gram_pus cells minus;few,Gram_pus cells<10 / lpf,Gram_pus cells<10/lpf,Org_1 klebsiella pneumoniae 2 proteus mirabilis,Org_1 klebsiella pneumoniae 2 methicillin resistant staphylococcus aureus,Org_1 proteus mirabilis 2 klebsiella pneumoniae,Org_1 pseudomonas aeruginosa 2 klebsiella pneumoniae,Org_1 klebsiella pneumoniae 2 proteus mirabilis,Org_1 klebsiella pneumoniae 2 pseudomonas aeruginosa,Org_1 klebsiella pneumoniae 2 proteus mirabilis,Org_1 methicillin resistant staphylococcus aureus 2 pseudomonas aeruginosa,Org_1 proteus mirabilis,Org_1 proteus mirabilis 2 pseudomonas aeruginosa,Org_2 pseudomonas aeruginosa,Org_acinetobacter baumannii,Org_acinetobacter species,Org_acinetobacter spp,Org_candida s pp,Org_candida species,Org_candida spp,Org_candida spp grown,Org_coagulase negative staphylococci seen,Org_coagulase negative staphylococcus,Org_e coli,Org_enterobacter aureus,Org_enterobacter cloacae,Org_enterobacter spp,Org_enterococcus faecium,Org_enterococcus fecalis,Org_enterococcus spp,Org_group a beta haemolytic streptococcus,Org_klebsiella pneumoniae,Org_methicillin resistant coagulase negative staphylococci,Org_methicillin resistant coagulase negative staphylococcus,Org_methicillin resistant cogulase negative staphylococcus,Org_methicillin resistant cogulase negative staphylococcus,Org_methicillin resistant staphylococcus aureus,Org_methicillin resistant staphylococcus epidermidis,Org_no growth,Org_no growth,Org_no growth after 48 hours of incubation,Org_no growth of pathogenic organism in culture,Org_no organism seen,Org_no pathogenic growth,Org_no pathogens grown,Org_no pathogens grown commensals isolated,Org_no pus cells,Org_no significant growth,Org_no turbidity seen,Org_non pathogenic growth,Org_non pathogenic organism growth,Org_non pathogenic organism growth,Org_nonminus,Org_pathogenic growth,Org_proteus mirabilis,Org_proteus vulgaris,Org_pseudomonas aeruginosa,Org_pseudomonas aeruginosaklebsiella pneumoniae,Org_pseudomonas putida,Org_pseudomonas spp,Org_staphylococcus aureus,Spec_abscess on left thigh,Spec_ascitic fluid,Spec_bal,Spec_bile,Spec_bile fluid,Spec_biological indicator,Spec_biological indicator of autoclave,Spec_biopsy,Spec_biopsy intramuscular paraspinal aspirate,Spec_blood,Spec_blood bag,Spec_blood bag unit no,Spec_blood bag unit no:,Spec_bloos bag unit no,Spec_bone,Spec_bone marrow aspirate,Spec_bone tip,Spec_breast abscess,Spec_c.s.f.,Spec_catheter tip,Spec_central line tip,Spec_conjunctive swab,Spec_csf,Spec_discharge,Spec_discharge from wound,Spec_discharge swab,Spec_e.t. secretions,Spec_e.t. tip,Spec_e.t. tube,Spec_empty bag tripal,Spec_empty blood bag,Spec_empty blood bag triple,Spec_endotracheal tube,Spec_et,Spec_et secretion,Spec_et tip,Spec_gauze from midline abdominal wound,Spec_granulation tissue,Spec_haematoma,Spec_hd catheter tip,Spec_hd tip,Spec_high vaginal swab,Spec_hvs,Spec_intercostal drain fluid,Spec_liver abscess,Spec_nail scraping,Spec_oral secretions,Spec_pancreatic fluid,Spec_pericardial fluid,Spec_peritoneal fluid,Spec_pleural fluid,Spec_pu,Spec_purulent discharge,Spec_pus,Spec_pus discharge,Spec_pus swab,Spec_radial head,Spec_right femoral catheter,Spec_scrotal tissue,Spec_sinus,Spec_slough,Spec_soft tissue,Spec_sputum,Spec_stool,Spec_suture site,Spec_swab,Spec_synovial fluid,Spec_throat swab,Spec_tip,Spec_tip uvc,Spec_tissue,Spec_tracheal tube swab,Spec_tracheostomy tube,Spec_triple sagam,Spec_ulcer swab,Spec_umbilical line,Spec_umbilical line tip,Spec_umbilical tip,Spec_urine,Spec_vaginal discharge,Spec_vaginal swab,Spec_vagnial swab,Spec_wound swab
0,592892.0,no sensitivity data,72.0,female,"no pus cells, no organisms seen",no growth,urine,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
1,646255.0,yes,39.0,female,"no pus cells, gram negative bacilli seen",acinetobacter spp,urine,general medicine,unknown,s,NaN,r,r,NaN,NaN,NaN,NaN,NaN,s,s,NaN,s,s,NaN,NaN,NaN,s,NaN,NaN,s,s,NaN,r,NaN,s,s,r,NaN,s,s,r,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
2,695323.0,no sensitivity data,16.0,male,no organisms seen,no growth (no turbidity seen),biological indicator (autoclave ),unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,695323.0,no sensitivity data,16.0,male,no organisms seen,no growth (no turbidity seen ),biological indicator (autoclave),unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,695323.0,no sensitivity data,16.0,male,minus;,no turbidity seen,biological indicator of autoclave,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,3008762.0,no sensitivity data,23.0,female,"many epithelial cells , no pus cells seen, gra...",candida spp,high vaginal swab,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
798,3008777.0,no sensitivity data,28.0,male,"no pus cells, no organisms seen",no growth,central line tip,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
799,3008777.0,no sensitivity data,28.0,male,"occasional pus cells, no organisms seen",no growth,pus,unknown,unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report


antibiotics = [
    "Amikacin", "Amoxicillin", "Amoxicillin+Clavulanic Acid", "Ampicillin",
    "Ampicillin+Sulbactam", "Azithromycin", "Aztreonam", "Benzyl Penicillin",
    "Cefazolin", "Cefepime", "Cefotaxime", "Cefoxitin", "Ceftazidime",
    "Ceftriaxone", "Cefuroxime", "Cephalexin", "Chloramphenicol",
    "Ciprofloxacin", "Clarithromycin", "Clindamycin", "Colistin",
    "Co-Trimoxazole", "Doripenem", "Ertapenem", "Erythromycin", "Gentamicin",
    "Imipenem", "Levofloxacin", "Linezolid", "Meropenem", "Norfloxacin",
    "Nitrofurantoin", "Piperacillin- Tazobactam", "Tigecycline",
    "Tobramycin", "Trimethoprim", "Trimethoprim/Sulfame Thoxale", "Vancomycin"
]

#  filling missing antibiotic results with "dc" 
fdf[antibiotics] = fdf[antibiotics].fillna("dc")

# separating features (X) and targets (y) 
X = fdf.drop(columns=antibiotics)
y = fdf[antibiotics].copy()

# one‐hot‐encoding all remaining categorical features 
X_enc = pd.get_dummies(X, drop_first=True)

# label‐encoding each antibiotic target to numeric classes 
label_encoders = {}
y_enc = pd.DataFrame(index=y.index)
for col in antibiotics:
    le = LabelEncoder()
    # fit on strings like 'R', 'S', 'dc', etc.
    y_enc[col] = le.fit_transform(y[col])
    label_encoders[col] = le

# train/test split 
X_train, X_test, y_train, y_test = train_test_split(
    X_enc, y_enc, test_size=0.2, random_state=42
)

# build & train the multi‐output Random Forest 
base_rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)
multi_rf = MultiOutputClassifier(base_rf, n_jobs=-1)
multi_rf.fit(X_train, y_train)

─
y_pred = multi_rf.predict(X_test)

accuracies = {}
for idx, col in enumerate(antibiotics):
    acc = accuracy_score(y_test[col], y_pred[:, idx])
    accuracies[col] = acc
    print(f"{col:30s} accuracy: {acc:.3f}")


avg_acc = sum(accuracies.values()) / len(accuracies)
print(f"\nAverage accuracy across all antibiotics: {avg_acc:.3f}")



print("\nClassification Reports:")
for idx, col in enumerate(antibiotics):
    print(f"\n--- {col} ---")
    # y_test[col] is your true (encoded) labels, y_pred[:, idx] your predictions
    print(classification_report(
        y_test[col],
        y_pred[:, idx]
    ))

Amikacin                       accuracy: 0.944
Amoxicillin                    accuracy: 0.994
Amoxicillin+Clavulanic Acid    accuracy: 0.969
Ampicillin                     accuracy: 0.963
Ampicillin+Sulbactam           accuracy: 1.000
Azithromycin                   accuracy: 0.994
Aztreonam                      accuracy: 0.994
Benzyl Penicillin              accuracy: 0.994
Cefazolin                      accuracy: 1.000
Cefepime                       accuracy: 0.912
Cefotaxime                     accuracy: 0.925
Cefoxitin                      accuracy: 0.994
Ceftazidime                    accuracy: 0.925
Ceftriaxone                    accuracy: 0.919
Cefuroxime                     accuracy: 0.950
Cephalexin                     accuracy: 1.000
Chloramphenicol                accuracy: 1.000
Ciprofloxacin                  accuracy: 0.931
Clarithromycin                 accuracy: 0.994
Clindamycin                    accuracy: 0.994
Colistin                       accuracy: 0.931
Co-Trimoxazole                 accuracy: 0.919
Doripenem                      accuracy: 0.988
Ertapenem                      accuracy: 0.925
Erythromycin                   accuracy: 0.994
Gentamicin                     accuracy: 0.931
Imipenem                       accuracy: 0.938
Levofloxacin                   accuracy: 0.938
Linezolid                      accuracy: 0.988
Meropenem                      accuracy: 0.938
Norfloxacin                    accuracy: 0.975
Nitrofurantoin                 accuracy: 0.969
Piperacillin- Tazobactam       accuracy: 0.956
Tigecycline                    accuracy: 1.000
Tobramycin                     accuracy: 0.988
Trimethoprim                   accuracy: 1.000
Trimethoprim/Sulfame Thoxale   accuracy: 1.000
Vancomycin                     accuracy: 0.988

Average accuracy across all antibiotics: 0.967

Classification Reports:

--- Amikacin ---
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       143
           1       0.50      0.50      0.50         6
           2       0.71      0.45      0.56        11

    accuracy                           0.94       160
   macro avg       0.73      0.65      0.68       160
weighted avg       0.94      0.94      0.94       160


--- Amoxicillin ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Amoxicillin+Clavulanic Acid ---
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       153
           2       0.25      0.50      0.33         2
           3       0.67      0.40      0.50         5

    accuracy                           0.97       160
   macro avg       0.64      0.63      0.61       160
weighted avg       0.97      0.97      0.97       160


--- Ampicillin ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.98       145
           1       0.79      0.79      0.79        14
           2       0.00      0.00      0.00         1

    accuracy                           0.96       160
   macro avg       0.59      0.59      0.59       160
weighted avg       0.96      0.96      0.96       160


--- Ampicillin+Sulbactam ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Azithromycin ---

c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Aztreonam ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       158
           2       1.00      1.00      1.00         1
           3       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.66      0.67      0.67       160
weighted avg       0.99      0.99      0.99       160


--- Benzyl Penicillin ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Cefazolin ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Cefepime ---
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       143
           1       0.43      0.33      0.38         9
           2       0.50      0.12      0.20         8

    accuracy                           0.91       160
   macro avg       0.62      0.48      0.51       160
weighted avg       0.89      0.91      0.89       160


--- Cefotaxime ---
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       145
           1       0.50      0.33      0.40         9
           2       1.00      0.17      0.29         6

    accuracy                           0.93       160
   macro avg       0.81      0.50      0.55       160
weighted avg       0.92      0.93      0.91       160


--- Cefoxitin ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Ceftazidime ---
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       144
           1       0.56      0.50      0.53        10
           2       1.00      0.17      0.29         6

    accuracy                           0.93       160
   macro avg       0.83      0.55      0.59       160
weighted avg       0.92      0.93      0.91       160


--- Ceftriaxone ---
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       146
           1       0.50      0.22      0.31         9
           2       0.00      0.00      0.00         5

    accuracy                           0.92       160
   macro avg       0.48      0.41      0.42       160
weighted avg       0.88      0.92      0.89       160


--- Cefuroxime ---
              precision    recall  f1-score   support

           0       0.96      0.99      0.98       151
           1       0.50      0.33      0.40         6
           2       0.00      0.00      0.00         3

    accuracy                           0.95       160
   macro avg       0.49      0.44      0.46       160
weighted avg       0.93      0.95      0.94       160


--- Cephalexin ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Chloramphenicol ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Ciprofloxacin ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       141
           1       0.50      0.60      0.55        10
           2       0.60      0.33      0.43         9

    accuracy                           0.93       160
   macro avg       0.69      0.64      0.65       160
weighted avg       0.93      0.93      0.93       160


--- Clarithromycin ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Clindamycin ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Colistin ---
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       147
           1       0.00      0.00      0.00         3
           2       0.75      0.30      0.43        10

    accuracy                           0.93       160
   macro avg       0.56      0.43      0.46       160
weighted avg       0.91      0.93      0.91       160


--- Co-Trimoxazole ---

c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       144
           1       0.56      0.38      0.45        13
           2       0.00      0.00      0.00         3

    accuracy                           0.92       160
   macro avg       0.51      0.46      0.48       160
weighted avg       0.91      0.92      0.91       160


--- Doripenem ---
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       158
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.33      0.33      0.33       160
weighted avg       0.98      0.99      0.98       160


--- Ertapenem ---
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       146
           1       0.40      0.33      0.36         6
           2       0.67      0.25      0.36         8

    accuracy                           0.93       160
   macro avg       0.67      0.52      0.56       160
weighted avg       0.91      0.93      0.91       160


--- Erythromycin ---
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       159
           1       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.50      0.50      0.50       160
weighted avg       0.99      0.99      0.99       160


--- Gentamicin ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       141
           1       0.56      0.50      0.53        10
           2       0.50      0.44      0.47         9

    accuracy                           0.93       160
   macro avg       0.68      0.65      0.66       160
weighted avg       0.93      0.93      0.93       160


--- Imipenem ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       142
           2       0.43      0.38      0.40         8
           3       0.67      0.60      0.63        10

    accuracy                           0.94       160
   macro avg       0.69      0.66      0.67       160
weighted avg       0.93      0.94      0.93       160


--- Levofloxacin ---
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       142
           1       0.50      0.56      0.53         9
           2       0.67      0.44      0.53         9

    accuracy                           0.94       160
   macro avg       0.72      0.66      0.68       160
weighted avg       0.93      0.94      0.93       160


--- Linezolid ---
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       158
           1       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.33      0.33      0.33       160
weighted avg       0.98      0.99      0.98       160


--- Meropenem ---
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       142
           1       0.50      0.38      0.43         8
           2       0.67      0.60      0.63        10

    accuracy                           0.94       160
   macro avg       0.71      0.66      0.68       160
weighted avg       0.93      0.94      0.93       160


--- Norfloxacin ---
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       154
           1       0.33      0.33      0.33         3
           2       1.00      0.33      0.50         3

    accuracy                           0.97       160
   macro avg       0.77      0.56      0.61       160
weighted avg       0.98      0.97      0.97       160


--- Nitrofurantoin ---
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       153
           1       0.40      0.67      0.50         3
           2       0.00      0.00      0.00         4

    accuracy                           0.97       160
   macro avg       0.46      0.56      0.50       160
weighted avg       0.95      0.97      0.96       160


--- Piperacillin- Tazobactam ---

c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       155
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         3

    accuracy                           0.96       160
   macro avg       0.32      0.33      0.33       160
weighted avg       0.94      0.96      0.95       160


--- Tigecycline ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Tobramycin ---
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       158
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.33      0.33      0.33       160
weighted avg       0.98      0.99      0.98       160


--- Trimethoprim ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Trimethoprim/Sulfame Thoxale ---
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       160

    accuracy                           1.00       160
   macro avg       1.00      1.00      1.00       160
weighted avg       1.00      1.00      1.00       160


--- Vancomycin ---
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       158
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         1

    accuracy                           0.99       160
   macro avg       0.33      0.33      0.33       160
weighted avg       0.98      0.99      0.98       160

c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Rishika_PC\Projects\Incubate\incubate_2025\myenv\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [44]:
fdf.to_csv("C:/Rishika_PC/Projects/Incubate/incubate_2025/proprocessed_data.csv", index=False)

In [55]:
# this keeps the “row” dimension, so it's 2-D
single_row_df = X_test.iloc[[19]]

#print(single_row_df)
# now predict
y_pred = multi_rf.predict(single_row_df)

In [56]:
print(y_pred)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0]]

In [ ]:
import pandas as pd
import numpy as np
import pprint

# 1.  reconstructing the true feature list straight from the model


first_tree = multi_rf.estimators_[0]

if hasattr(first_tree, "feature_names_in_"):
    train_cols = list(first_tree.feature_names_in_)
else:                                   # fallback (older scikit-learn)
    # Here we *must* already have saved train_cols earlier.  If not,
    # raise an explicit error so you know to set it.
    try:
        train_cols = train_cols         # noqa: F821
    except NameError:
        raise RuntimeError(
            "train_cols not found — save it right after you build X_enc:\n"
            "   train_cols = list(X_enc.columns)"
        )

expected_len = len(train_cols)
print(f"Model expects {expected_len} features.")


# 2.  building a zero-filled Series with ALL expected columns

def zero_feature_vector():
    return pd.Series(0, index=train_cols, dtype=float)


# 3.  helper for turning a raw 9-field dict into that vector

def feature_vector_from_raw(raw):
    fv = zero_feature_vector()

    # numeric survivors
    for num in ["UMR No.", "Age", "Colony Count"]:
        if num in fv.index:
            fv[num] = float(raw[num])

    # simple categoricals
    def activate(base, val):
        col = f"{base}_{val.strip()}"
        if col in fv.index:
            fv[col] = 1
    activate("Reports Photo", raw["Reports Photo"])
    activate("Gender",        raw["Gender"])
    activate("Department",    raw["Department"])

    # Gram Stain (multi)
    for g in split_gram(raw["Gram Stain"]):
        col = f"Gram_{g}"
        if col in fv.index:
            fv[col] = 1

    # Organism Isolated (multi)
    for o in split_org(clean_org(raw["Organism Isolated"])):
        col = f"Org_{o}"
        if col in fv.index:
            fv[col] = 1

    # Specimen Type (single)
    spec = clean_specimen(raw["Specimen Type"])
    spec_col = f"Spec_{spec}"
    if spec_col in fv.index:
        fv[spec_col] = 1

    return fv.to_numpy().reshape(1, -1)   # shape (1, expected_len)


# 4.  prediction wrapper

def predict_antibiotics(raw):
    X_vec = feature_vector_from_raw(raw)
    # final safety check
    assert X_vec.shape[1] == expected_len, \
        f"Vector length {X_vec.shape[1]} vs model expects {expected_len}"
    codes = multi_rf.predict(X_vec)[0]
    return {
        ab: label_encoders[ab].inverse_transform([codes[i]])[0]
        for i, ab in enumerate(antibiotics)
    }


# 5.  testing with manual samples

'''sample = {
    "UMR No.":             695323,
    "Reports Photo":      "no sensitivity data",
    "Age":                   16,
    "Gender":              "male",
    "Gram Stain":          "no organisms seen",
    "Organism Isolated":   "no growth",
    "Specimen Type":       "blood bag unit no 2788 plt (00c13691",
    "Department":          "unknown",
    "Colony Count":         0
}'''
sample = {
    "UMR No.":             646255,
    "Reports Photo":      "yes",
    "Age":                   39,
    "Gender":              "female",
    "Gram Stain":          "no pus cells, gram negative bacilli seen",
    "Organism Isolated":   "acinetobacter spp",
    "Specimen Type":       "urine",
    "Department":          "general medicine",
    "Colony Count":        "unknown"
}


pprint.pprint(predict_antibiotics(sample))

Model expects 766 features.
{'Amikacin': 's',
 'Amoxicillin': 'dc',
 'Amoxicillin+Clavulanic Acid': 'dc',
 'Ampicillin': 'r',
 'Ampicillin+Sulbactam': 'dc',
 'Azithromycin': 'dc',
 'Aztreonam': 'dc',
 'Benzyl Penicillin': 'dc',
 'Cefazolin': 'dc',
 'Cefepime': 's',
 'Cefotaxime': 'dc',
 'Cefoxitin': 'dc',
 'Ceftazidime': 'dc',
 'Ceftriaxone': 'dc',
 'Cefuroxime': 'dc',
 'Cephalexin': 'dc',
 'Chloramphenicol': 'dc',
 'Ciprofloxacin': 's',
 'Clarithromycin': 'dc',
 'Clindamycin': 'dc',
 'Co-Trimoxazole': 's',
 'Colistin': 'dc',
 'Doripenem': 'dc',
 'Ertapenem': 'r',
 'Erythromycin': 'dc',
 'Gentamicin': 's',
 'Imipenem': 's',
 'Levofloxacin': 'r',
 'Linezolid': 'dc',
 'Meropenem': 's',
 'Nitrofurantoin': 'dc',
 'Norfloxacin': 'dc',
 'Piperacillin- Tazobactam': 'dc',
 'Tigecycline': 'dc',
 'Tobramycin': 'dc',
 'Trimethoprim': 'dc',
 'Trimethoprim/Sulfame Thoxale': 'dc',
 'Vancomycin': 'dc'}